### PR TITLE
Load application_policy in first to prevent require error

### PR DESCRIPTION
**Pull request by I-Iugo**
If you don't make sure load application_policy in first when you'll have a inheritance you'll have error.

### CODE REVIEW

**Comment by I-Iugo** [comment]
@smartinm If you're ok, could you merge this?

**Comment by smartinm** [comment]
Sorry for the delayed response. The application_policy.rb is not a mandatory and the require will fail if the file does not exist.
Please, check if explicitly require application_policy from your policies files solves your problem: https://stackoverflow.com/questions/33479847/reliable-require-of-multiple-files-while-respecting-dependencies

**Comment by I-Iugo** [comment]
Thanks

**Comment by I-Iugo** [comment]
Hello

Ok ok, thanks for your fixed and I close the PR
Hugo POULIQUEN

**Pull request closed without merging**
